### ISSUE TITLE
Flatpak version of Pulsar does not follow system theme properly

### ISSUE THREAD

**Issue by aylamz** [flathub/dev.pulsar_edit.Pulsar#3]
This is what the flatpak version looks like: (The menubar is white even though dark theme is used for both the desktop and for Pulsar)
![pulsar-flatpak](https://user-images.githubusercontent.com/85757201/224482414-2455860f-1286-495c-b7d2-a63cec890f63.png)

This is how I expect it to look, and how it does look if I install pulsar as RPM:
![flatpak-rpm](https://user-images.githubusercontent.com/85757201/224482487-39a4fcfe-0707-4987-a9a1-7d52a31d722d.png)

System: Fedora 37 KDE spin, Wayland

**Comment by cat-master21** [comment]
This is an issue with Pulsar, https://github.com/pulsar-edit/pulsar/issues/422. Though as for the menubar not syncing with the system theme is an issue with the flatpak version.

**Comment by cat-master21** [comment]
Thanks for the feedback @aylamz I will close this issue then.

**Comment by aylamz** [comment]
Update: I re-installed Fedora and this issue has appeared again for some reason. Pulsar is not the only Flatpak that does not follow system theme properly though so maybe this is a Fedora or KDE issue. I'll open an issue on KDE bugtracker to see what they think.

**Comment by confused-Techie** [comment]
I do want to chime in real quick to say I have an [open PR](https://github.com/pulsar-edit/pulsar/pull/545) within Pulsar to address part of this issue. This PR specifically aims to change the Pulsar window theme along with the **theme used within Pulsar** it does nothing to address the theme matching the system theme.

If the folks here would like to test this behavior and see how it works within the flakpak version I'd be glad to hear if it improves the situation.

Elsewhere within Pulsar we are seeing mixed success with this PR. It seems the Window Theme of the Pulsar application doesn't change as we would expect within some platforms due to issues with our current Electron version. But this PR does show promise to change the Menu Bar theme properly.
