### ISSUE TITLE
When I run the flatpak version in KDE Plasma, I get a warning telling me that an app is trying to access my "wallet". This doesn't happen with other packages like the AUR version

### ISSUE THREAD

**Issue by Boux** [flathub/dev.pulsar_edit.Pulsar#49]
I originally posted this issue directly in the Pulsar github where they recommended I post it here: https://github.com/pulsar-edit/pulsar/issues/1017

Here's the gist of it:

I get this warning 50% of the time I open Pulsar through flatpak:
![image](https://github.com/pulsar-edit/pulsar/assets/2771413/63edbda2-a603-4a7a-afc8-0b24ee99834d)

I'm currently using KDE Plasma on Arch, everything is up to date

I have tried both the AUR and Flatpak versions of Pulsar, and only the flatpak seems to give me the error, this tells me that the flatpak is compromised in some way.

Here's a video of me opening the AUR version a bunch and not getting the warning (0:00 - 0:36), and then opening the Flatpak version a bunch and getting the warning 50% of the time (0:38 - 1:13):

https://github.com/pulsar-edit/pulsar/assets/2771413/b209fdaa-2f0d-4150-82d9-9a3e79c53bc3

**Comment by cat-master21** [comment]
Thanks for opening this @Boux, this is [a bug in kwallet](https://bugs.kde.org/show_bug.cgi?id=487348) and in other Flatpak apps that use the freedesktop secrets portal. Kwallet recently has a [fix merged](https://invent.kde.org/frameworks/kwallet/-/merge_requests/84) so it should be in Arch soon. I will mark this as closed since this is (to be) fixed and not a Pulsar (Flatpak) specific issue.
